[projet]
nom = "noliae-discord-bot"
version = "0.1.0"
entree = "src/main.nol"
auteur = "Noliae France"
licence = "MIT"
description = "Bot Discord Noliae écrit en Nolc"

[dependances]
nolc-discord = { git = "https://github.com/Noliae-France/nolc-discord.git" }
